### ISSUE TITLE
EJS template

### ISSUE THREAD

**Issue by Linux-localhost** [Linux-localhost/Chubby-racoon#10]
Maybe we can look into EJS templates for our front-end,

We are using templates in the current file:
\views\index.ejs

These templates are stored in our \views\includes folder

**Comment by rosavoogd** [comment]
working on the footer.ejs for the html and css

**Comment by Linux-localhost** [comment]
Includes now contains:

Error-message
footer
home
login
introduce
likenav
nav
register
sucess-message
forgot-password
