### ISSUE TITLE
Team name

### ISSUE THREAD

**Issue by Linux-localhost** [Linux-localhost/Chubby-racoon#27]
We need a cool team name any suggestions? :)

**Comment by rosavoogd** [comment]
I was thing MeetMe, or LetsConnect

**Comment by Linux-localhost** [comment]
[
HoneyRomance
Loveling
Lovery
Heartal
loveSight
Promance
Dateback
Dateful
DetailDate
ToprankDate
Datebefore
Datemagnet
InstyleLove
EarthlyLove
Loveserenity
LoveSiren
Flerting
Forevir
DreamyCrush



]

**Comment by mikehov** [comment]
Lovely, 
TheRelationShip,
