### ISSUE TITLE
Fixing swipe common bugs

### ISSUE THREAD

**Issue by Linux-localhost** [Linux-localhost/Chubby-racoon#28]
Hey @mikehov,

Can you pull the master and check if you encounter any bugs while swiping? Let us know the results

**Comment by Linux-localhost** [comment]
Reworking swipe feature, currently it is broken

**Comment by Linux-localhost** [comment]
Deleted everything and started over what do you think @mikehov

**Comment by mikehov** [comment]
I see I see, this looks like a better solution to me than what I thought it mind. Naazzzzz
