### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rosavoogd** [Linux-localhost/Chubby-racoon#35]
Making a logo for TheRelationShip app

**Comment by mikehov** [comment]
I made the logo, here it is. 
![logo-therelationship](https://user-images.githubusercontent.com/22232236/85201706-d0582c00-b301-11ea-8db5-cf9cbc143b83.png)

**Comment by mikehov** [comment]
![logo-therelationship](https://user-images.githubusercontent.com/22232236/85201723-f251ae80-b301-11ea-8f5c-456cbaec629f.png)

**Comment by rosavoogd** [comment]
nice!
