### ISSUE TITLE
Update wiki

### ISSUE THREAD

**Issue by Linux-localhost** [Linux-localhost/Chubby-racoon#9]
I think we need to update our wiki with new information:

* decisions we have made and why
* Update the color palette

Any other relevant information we can update our wiki with

![afbeelding](https://user-images.githubusercontent.com/66538083/84126659-7ec8bb00-aa3e-11ea-882f-395acff83c4f.png)

**Comment by rosavoogd** [comment]
color palette updated

**Comment by Linux-localhost** [comment]
We need to update our wiki with new information, I will check when I can write something down

**Comment by rosavoogd** [comment]
Yes, I will also write some of my own progress down and somethings about our communication and teamwork tomorrow or monday!

**Comment by Linux-localhost** [comment]
I made some topics for you and linked them to the correct pages, also made a image folder within the wiki. You can store the images there and link them

**Comment by rosavoogd** [comment]
Could you link the image folder? I don't see it.

**Comment by Linux-localhost** [comment]
> 
> 
> Could you link the image folder? I don't see it.

Mentioned it in discord ;)

**Comment by Linux-localhost** [comment]
Updated wiki with a bunch of resources, information
